version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: chat-app-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: chat-app-dev
    volumes:
      - chat-app-data:/var/lib/postgresql/data

volumes:
  chat-app-data:
